image:
  pullPolicy: IfNotPresent
  repository: 
  tag: latest
  imagePullSecrets:

service:
  ports:
    - name: http
      value: 80

deployment:
  replicaCount: 1
  # livenessHttpGet: "/health-check"
  # readinessHttpGet: "/health-check"
  # failureThreshold: 3
  # initialDelaySeconds: 0
  envFrom: {}
  environments:
    # SAMPLE_ENV: "ENV_VALUE"

secrets:
  enabled: false
  values:
    - name: ""
      data:
        # SAMPLE_ENV: "ENV_VALUE"

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # ingress.kubernetes.io/ssl-redirect: "False"
    # nginx.org/websocket-services: svc-1
  rules:
    - host: 
      paths:
        - path: /
          port: 80
  # tls:
  #   - secretName:
  #     hosts:
  #       - 
  
resources:
  limits: {}
    # cpu: 100m
    # memory: 2048Mi
  requests:
    cpu: 100m
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}

pvc:
  enabled: false
  # name: "lemon"
  # storage: 5Gi
  # storageClassName: storage-class-name
  # accessMode: ReadWriteOnce
  # mountPath: ""

pv:
  enabled: false
  # name: "lemon"
  # storage: 5Gi
  # storageClassName: storage-class-name
  # accessMode: ReadWriteOnce
  # nfs:
  #   path: ""
  #   server: ""