{{- $module := .Values.service -}}
{{- $fullName := printf "%s-%s" (include "baseName.fullname" .) ($module.name | default "") | trunc 63 | trimSuffix "-" -}}
{{- $name := printf "%s-%s" (include "baseName.name" .) ($module.name | default "") | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ include "baseName.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.image.pu }}
      imagePullSecrets:
       - name: {{ .Values.global.image.pullSecret }} 
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }} 
      {{- end }}
      containers:
        {{- if .Values.deployment.containers }}
        {{- range $container := .Values.deployment.containers }}
            {{- include "lemon-k8s.containerBody" (dict "root" $ "Values" $.Values "container" $container) | nindent 8 }}
        {{- end }}
        {{- else }}
        - name: fallback-container
          image: busybox
          command: [ "sleep", "3600" ]
        {{- end }}
    
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.deployment.volumes }}
      {{- toYaml .Values.deployment.volumes | default "" | nindent 8 }} 
      {{- end }}
      {{- if and (.Values.pvc) (.Values.pvc.enabled) }}
        - name: {{ $fullName }}
          persistentVolumeClaim:
            claimName: {{ $fullName }}
      {{- end }}

