{{- if and (.Values.secrets) (.Values.secrets.enabled) -}}
{{- range .Values.secrets.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
