{{- if and (.Values.secret) (.Values.secret.enabled) -}}
{{- $module := .Values.service -}}
{{- $fullName := printf "%s-%s" (include "baseName.fullname" .) ($module.name | default "") | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default $fullName }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
