{{- $module := .Values.service -}}
{{- if or ($module.imageTag) (.Values.image.tag) -}}
{{- $fullName := printf "%s-%s" (include "baseName.fullname" .) ($module.name | default "") | trunc 63 | trimSuffix "-" -}}
{{- $name := printf "%s-%s" (include "baseName.name" .) ($module.name | default "") | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ include "baseName.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if $module.headless }}
  clusterIP: None
  {{- else if eq $module.type "NodePort" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    {{- range $_, $port := $module.ports }}
    - name: {{ $port.name }}
      port: {{ $port.value }}
      targetPort: {{ $port.value }}
      protocol: TCP
      {{- if eq $module.type "NodePort" }}
      nodePort: {{ $port.nodePort | default 0 }}
      {{- end }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
